// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsEuKoIT0FkJj3GavQEcsj955ANwydWy8',
    appId: '1:639932995170:web:391be026e5645c4ee3233b',
    messagingSenderId: '639932995170',
    projectId: 'weesaviya-mobile',
    authDomain: 'weesaviya-mobile.firebaseapp.com',
    storageBucket: 'weesaviya-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG5ZUe29DuqyvvRVSNdMkatPF67TO4hDg',
    appId: '1:639932995170:android:a00da51a90ba4c7be3233b',
    messagingSenderId: '639932995170',
    projectId: 'weesaviya-mobile',
    storageBucket: 'weesaviya-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-sF9ssS3bzS1uJoMmpLyK_NyAVPI019g',
    appId: '1:639932995170:ios:ec93c5c08b2032b0e3233b',
    messagingSenderId: '639932995170',
    projectId: 'weesaviya-mobile',
    storageBucket: 'weesaviya-mobile.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-sF9ssS3bzS1uJoMmpLyK_NyAVPI019g',
    appId: '1:639932995170:ios:ec93c5c08b2032b0e3233b',
    messagingSenderId: '639932995170',
    projectId: 'weesaviya-mobile',
    storageBucket: 'weesaviya-mobile.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );
}
